### ISSUE TITLE
Add negation syntax for headers

### ISSUE THREAD

**Issue by decoomanj** [Neofonie/aiko#6]
Sometimes you want to explicitly test if certain headers are missing. 

A possible syntax could be;

```
headers:
  - !Content-Type
```

**Comment by j-musca** [comment]
@decoomanj The exclamation mark is a reserved keyword in yaml. It would be much easier to introduce a new field "forbiddenHeaders", "illegalHeaders", etc.

**Comment by j-musca** [comment]
Current format

```
  response:
    headers:
      Content-Type: 'application/json; charset=utf-8'
    status: 201
```

Option "new field"

```
  response:
    headers:
      Content-Type: 'application/json; charset=utf-8'
    forbiddenHeaders:
      - X-Custom-Header-0
      - X-Custom-Header-1
    status: 201
```

Option "using headers field"

```
  response:
    headers:
      Content-Type: 'application/json; charset=utf-8'
      "!X-Custom-Header-0":
      "!X-Custom-Header-1":
    status: 201
```
